#!/usr/bin/env ruby

SingRoot = File.dirname __FILE__

def singroot file
  File.join SingRoot, file
end

require singroot 'db/setup.rb'
require singroot 'lib/importer.rb'

unless defined? Pry
  case ARGV[0]
  when 'init'
    require singroot 'db/create.rb'
  when 'import'
    if File.directory(ARGV[1])
      Importer.run(ARGV[1])
    else
      puts 'usage: sing import <directory>'
    end
  else
    puts 'usage: sing <command>'
  end
end