#!/usr/bin/env ruby

require('./db/setup.rb')
require('./lib/importer.rb')

case ARGV[0]
when 'import'

  if File.directory(ARGV[1])
    Importer.run(ARGV[1])
  else
    puts 'usage: sing import <directory>'
  end
else
  puts 'usage: sing <command> <args>'
end
